POST localhost:8080/admin/command/start
Content-Type: application/json

{
  "coinType": "ETHEREUM",
  "coinExchangeType": "UPBIT",
  "tradingTerm": "SCALPING",
  "strategyCode": "RSI"
}


###
POST localhost:8080/admin/command/stop
Content-Type: application/json

{
  "coinType": "ETHEREUM",
  "coinExchangeType": "UPBIT",
  "tradingTerm": "SCALPING",
  "strategyCode": "RSI"
}
###