POST localhost:8080/autotrading/register
Content-Type: application/json
userId: 1234

{
  "title": "테스트입니다",
  "coinType": "ETHEREUM",
  "coinExchangeType": "UPBIT",
  "tradingTerm": "SCALPING",
  "strategyCode": "RSI",
  "keyPairId": "30a0cd03-7900-42ba-b87a-e84eeed11e90"
}


###
POST localhost:8080/autotrading/21667114-1889-4066-beba-e5a6f07e7110/start
Content-Type: application/json
userId: 1234

###
POST localhost:8080/autotrading/50caaa98-d9e6-4abe-9702-9ebce1e8c6d4/stop
Content-Type: application/json
userId: 1234

###
POST localhost:8080/autotrading/50caaa98-d9e6-4abe-9702-9ebce1e8c6d4/terminate
Content-Type: application/json
userId: 1234

###