POST localhost:8080/trading/autotrading/command/START
Content-Type: application/json

{
  "coinType": "ETHEREUM",
  "coinExchangeType": "UPBIT",
  "tradingTerm": "SCALPING",
  "strategyCode": "RSI"
}


###
POST localhost:8080/trading/autotrading/command/STOP
Content-Type: application/json

{
  "coinType": "ETHEREUM",
  "coinExchangeType": "UPBIT",
  "tradingTerm": "SCALPING",
  "strategyCode": "RSI"
}
###