### 거래소 키 등록
POST http://localhost:8080/coin/exchange-key/register
Content-Type: application/json

{
  "exchangeType": "UPBIT",
  "accessKey": "access key",
  "secretKey": "secret key"
}

### 자동매매 등록
POST http://localhost:8080/coin/autotrade/register
Content-Type: application/json

{
  "coinStrategyType": "EXAMPLE",
  "exchangeType": "UPBIT",
  "coinTypes": [
    "BITCOIN",
    "ETHEREUM",
    "SOLANA"
  ],
  "candleUnits": [
    "UNIT_1M",
    "UNIT_3M"
  ],
  "keyPairId": "354db64e-e208-4dc3-ab8b-8478ab55dc89",
  "config": {
    "configA": "TESTA",
    "configB": 123
  }
}

### 서버에 거래소 캔들 정보 저장
POST http://localhost:8080/coin/chart/load
Content-Type: application/json

{
  "exchangeType": "UPBIT",
  "coinTypes": [
    "BITCOIN",
    "ETHEREUM",
    "SOLANA"
  ],
  "candleUnits": [
    "UNIT_1M",
    "UNIT_3M",
    "UNIT_5M",
    "UNIT_10M",
    "UNIT_15M",
    "UNIT_30M",
    "UNIT_60M",
    "UNIT_240M"
  ],
  "startDateTime": "2023-01-01T00:00:00",
  "endDateTime": "2023-04-01T00:00:00",
  "keyPairId": "354db64e-e208-4dc3-ab8b-8478ab55dc89"
}

### 백테스트 (비트코인 차트 검증용)
POST http://localhost:8080/coin/autotrade/backtest
Content-Type: application/json

{
  "startDateTime": "2023-02-15T00:00:00",
  "endDateTime": "2023-03-31T00:00:00",
  "durationUnit": "UNIT_1M",
  "coinStrategyType": "UPBIT_CHART_VALIDATE",
  "exchangeType": "BACKTEST_UPBIT",
  "coinTypes": [
    "BITCOIN"
  ],
  "candleUnits": [
    "UNIT_1M",
    "UNIT_15M"
  ],
  "config": {
    "onceTradeAmount": 100000
  }
}

### 백테스트
POST http://localhost:8080/coin/autotrade/backtest
Content-Type: application/json

{
  "startDateTime": "2023-02-15T00:00:00",
  "endDateTime": "2023-03-31T00:00:00",
  "durationUnit": "UNIT_1M",
  "coinStrategyType": "EXAMPLE",
  "exchangeType": "BACKTEST_UPBIT",
  "coinTypes": [
    "BITCOIN",
    "ETHEREUM",
    "SOLANA"
  ],
  "candleUnits": [
    "UNIT_15M"
  ],
  "config": {
    "onceTradeAmount": 100000
  }
}


### 백테스트 결과 조회
GET http://localhost:8080/coin/backtest/BACKTEST-7d49641a-ddd2-468b-aa7d-f86cddcb18f5

### 자동매매 시작
POST http://localhost:8080/coin/autotrade/BACKTEST-351d3add-c676-4b27-9b34-0843572fd726/start
Content-Type: application/json

### 자동매매 정지
POST http://localhost:8080/coin/autotrade/160f2665-4f86-4d19-b6bf-7ef3f4fede46/stop
Content-Type: application/json

### 자동매매 제거
POST http://localhost:8080/coin/autotrade/bdb74ff9-2d3a-4494-8ed4-70995ae7b748/terminate
Content-Type: application/json