rootProject.name = "autotrading"
include(":application-deploy")
include(":application-deploy:coin-spot")
include(":application-deploy:coin-futures")
include(":application-infra")
include(":application-infra:auth")
include(":application-infra:client")
include(":application-infra:common")
include(":application-infra:persistence")
include(":application-view")
include(":application-view:dashboard")