rootProject.name = "autotrading"
include(":application-service")
include(":application-service:coin-spot")
include(":application-service:coin-futures")
include(":application-infra")
include(":application-infra:auth")
include(":application-infra:client")
include(":application-infra:common")
include(":application-infra:persistence")
include(":application-view")
include(":application-view:dashboard")