ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
= API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:docinfo: shared-head
:operation-curl-request-title: curl
:operation-http-request-title: request http
:operation-path-parameters-title: request path parameters
:operation-request-parameters-title: request params
:operation-request-headers-title: request headers
:operation-request-body-title: request body
:operation-http-response-title: response http
:operation-response-body-title: response body
:operation-response-fields-title: response fields

== CoinAutoTrading
// 템플릿 종류
// 요청 : operation::/admin/command[snippets='curl-request,http-request,request-headers,path-parameters,request-parameters,request-fields']
// 응답 : operation::/admin/command[snippets='http-response,response-fields']

=== 자동매매 등록 API
==== 설명
----
자동매매 등록 API
----
==== 요청
operation::/trading/autotrading/register[snippets='http-request,request-headers,request-fields']
==== 응답
operation::/trading/autotrading/register[snippets='http-response,response-fields']


=== 자동매매 시작 API
==== 설명
----
자동매매 시작 API
----
==== 요청
operation::/trading/autotrading/start[snippets='http-request,request-headers,path-parameters']
==== 응답
operation::/trading/autotrading/start[snippets='http-response,response-fields']


=== 자동매매 정지 API
==== 설명
----
자동매매 정지 API
----
==== 요청
operation::/trading/autotrading/stop[snippets='http-request,request-headers,path-parameters']
==== 응답
operation::/trading/autotrading/stop[snippets='http-response,response-fields']


=== 자동매매 제거 API
==== 설명
----
자동매매 제거 API
----
==== 요청
operation::/trading/autotrading/terminate[snippets='http-request,request-headers,path-parameters']
==== 응답
operation::/trading/autotrading/terminate[snippets='http-response,response-fields']



=== 거래소 키 등록 API
==== 설명
----
거래소 키 등록 API
----
==== 요청
operation::/auth/key[snippets='http-request,request-headers,request-fields']
==== 응답
operation::/auth/key[snippets='http-response,response-fields']


=== 사용자 거래소 키 조회 API
==== 설명
----
사용자 거래소 키 조회 API
----
==== 요청
operation::/auth/user/key[snippets='http-request,request-headers,path-parameters']
==== 응답
operation::/auth/user/key[snippets='http-response,response-fields']